name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
    - name: Build
      run: dotnet build -c Release
    - name: Package
      run: dotnet pack -o ./packaged --no-build
    - name: Publish packages
      run: for i in ./packaged/TerevintoSoftware.Integrator* ; do dotnet nuget push $i -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate ; done 
